### ISSUE TITLE
Quoting in dbt_project_yml not used correctly

### ISSUE THREAD

**Issue by aurany** [fishtown-analytics/dbt-adapter-tests#14]
I'm trying to create an adapter for IBM DB2. In my spec-file i have

```
projects:
  - overrides: base
    paths:
      models/view_model.sql: |
        {{ config(materialized='view') }}
        select * from sysibm.sysdummy1
    dbt_project_yml:
      quoting:
        database: false
        schema: true
        identifier: true
```

This is working in some cases/tests, for example

```
CREATE VIEW testdb."dbt_test_210210204959161102758925"."view_model__dbt_tmp" AS
  
select * from sysibm.sysdummy1
```
_EDIT: The reason for overriding the view_model is to get rid of the default quoting._

...but in some cases/tests it goes wrong. This case/test will fail because database is quoted and the identifier is not.

`select count(*) as num_rows from "testdb"."dbt_test_210210204959161102758925".base`

I assume something goes wrong in the _relation_from_name function but i'm not sure how to fix it, and I do not understand why this happens only in some tests.

// R
