### ISSUE TITLE
Not fully compatible with dbt-core 0.19.0rc1

### ISSUE THREAD

**Issue by dbeatty10** [fishtown-analytics/dbt-adapter-tests#9]
### Describe the bug
Two test specifications within dbt-adapter-tests aren't compatible with dbt-core 0.19.0rc1:
- data_test
- data_test_ephemeral_models

### Steps To Reproduce
1. Install dbt 0.19.0rc1
2. Create a test configuration for Postgres
    - see below for an example `*.dbtspec` file
3. Run the test config
    - with a command like `pytest -v test/integration/postgres-13.dbtspec`

#### `test/integration/postgres-13.dbtspec` example
```yaml
target:
  type: postgres
  host: localhost
  user: postgres
  pass: ********************
  port: 5432
  dbname: postgres
  schema: dbt_test_{{ var('_dbt_random_suffix') }}

sequences:
  test_dbt_data_test: data_test
  test_dbt_ephemeral_data_tests: data_test_ephemeral_models
```

### Expected behavior
I expected all the standard tests to pass for dbt-postgres v0.19.0rc1 (since it is a Fishtown-supported database adapter).

### Screenshots and log output
Log output (drastically truncated):

```
_________________________________________________________ usecase: test_dbt_data_test __________________________________________________________
usecase execution failed
   spec failed: ("Invalid result, missing required key 'node'",)
   no further details known at this point.
------------------------------------------------------------- Captured stdout call -------------------------------------------------------------
```
(snip)
```
test/integration/postgres-13.dbtspec::test_dbt_data_test FAILED
test/integration/postgres-13.dbtspec::test_dbt_ephemeral_data_tests FAILED
```

### System information
**Which database are you using dbt with?**
- postgres

Although I only tested this against Postgres, I would expect this same problem to affect all the databases supported by Fishtown Analytics as well as all community-supported plugins.

**The output of `dbt --version`:**
```
installed version: 0.19.0-rc1
   latest version: 0.18.1

Your version of dbt is ahead of the latest release!

Plugins:
  - postgres: 0.19.0rc1
```

### Additional context
I've got a simple workaround that I'll submit as a pull request.
